//
//  WeatherMockData.swift
//  JennyWeather
//
//  Created by Brett Petersen on 2/12/20.
//  Copyright © 2020 Brett Petersen. All rights reserved.
//

import Foundation

class WeatherMockData {
	static func getWeatherViewModel() throws -> WeatherViewModel {
		let json = try jsonString.toJson()
		let dto: WeatherDTO = try NetworkUtility.codableFromJSON(json)
		let weatherVM = WeatherViewModel(dto: dto)
		return weatherVM
	}
}

extension WeatherMockData {
    static var jsonString: String {
        let string = """
        {
           "currentWeather":{
              "rainfallAmount":{
                 "pastSixHours":{
                    "value":0,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.001
                       },
                       "symbol":"mm"
                    }
                 },
                 "pastHour":{
                    "value":0,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.001
                       },
                       "symbol":"mm"
                    }
                 },
                 "pastTwentyFourHours":{
                    "value":0,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.001
                       },
                       "symbol":"mm"
                    }
                 }
              },
              "condition":"partlyCloudy",
              "humidity":0.51000000000000001,
              "precipitationIntensity":{
                 "value":0,
                 "unit":{
                    "converter":{
                       "constant":0,
                       "coefficient":2.7776999999999998e-07
                    },
                    "symbol":"mm/h"
                 }
              },
              "temperature":{
                 "value":19.239999999999998,
                 "unit":{
                    "converter":{
                       "constant":273.14999999999998,
                       "coefficient":1
                    },
                    "symbol":"°C"
                 }
              },
              "isDaylight":true,
              "cloudCover":0.51000000000000001,
              "symbolName":"cloud.sun",
              "pressureTrend":"steady",
              "dewPoint":{
                 "value":8.8800000000000008,
                 "unit":{
                    "converter":{
                       "constant":273.14999999999998,
                       "coefficient":1
                    },
                    "symbol":"°C"
                 }
              },
              "uvIndex":{
                 "value":6,
                 "category":"high"
              },
              "snowfallAmount":{
                 "pastSixHours":{
                    "value":0,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.001
                       },
                       "symbol":"mm"
                    }
                 },
                 "pastHour":{
                    "value":0,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.001
                       },
                       "symbol":"mm"
                    }
                 },
                 "pastTwentyFourHours":{
                    "value":0,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.001
                       },
                       "symbol":"mm"
                    }
                 }
              },
              "date":703795524,
              "visibility":{
                 "value":29690.650000000001,
                 "unit":{
                    "converter":{
                       "constant":0,
                       "coefficient":1
                    },
                    "symbol":"m"
                 }
              },
              "wind":{
                 "gust":{
                    "value":11.33,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.27777800000000002
                       },
                       "symbol":"km/h"
                    }
                 },
                 "speed":{
                    "value":7.25,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":0.27777800000000002
                       },
                       "symbol":"km/h"
                    }
                 },
                 "compassDirection":"west",
                 "direction":{
                    "value":275,
                    "unit":{
                       "converter":{
                          "constant":0,
                          "coefficient":1
                       },
                       "symbol":"°"
                    }
                 }
              },
              "metadata":{
                 "expirationDate":703795824,
                 "latitude":37.831000000000003,
                 "longitude":-122.286,
                 "date":703795524
              },
              "apparentTemperature":{
                 "value":18.489999999999998,
                 "unit":{
                    "converter":{
                       "constant":273.14999999999998,
                       "coefficient":1
                    },
                    "symbol":"°C"
                 }
              },
              "pressure":{
                 "value":1025.0599999999999,
                 "unit":{
                    "converter":{
                       "constant":0,
                       "coefficient":100
                    },
                    "symbol":"mbar"
                 }
              }
           },
           "availability":{
              "minuteAvailability":"available",
              "airQualityAvailability":"unsupported",
              "alertAvailability":"available"
           },
           "dailyForecast":{
              "metadata":{
                 "attribution":{
                    "combinedMarkDarkURL":"https://weather-data.apple.com/assets/branding/combined-mark-dark.png",
                    "name":"Apple Weather",
                    "combinedMarkLightURL":"https://weather-data.apple.com/assets/branding/combined-mark-light.png",
                    "logoURL":"https://weather-data.apple.com/assets/branding/combined-mark-dark.png",
                    "squareMarkURL":"https://weather-data.apple.com/assets/branding/square-mark.png",
                    "legalPageURL":"https://weather-data.apple.com/legal-attribution.html",
                    "sourceURL":"https://weather-data.apple.com/legal-attribution.html",
                    "serviceName":"Apple Weather"
                 },
                 "expirationDate":703799124,
                 "latitude":37.831000000000003,
                 "longitude":-122.286,
                 "date":703795524
              },
              "forecast":[
                 {
                    "rainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "condition":"mostlyClear",
                    "humidity":0,
                    "wholeDayRainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "lowTemperature":{
                       "value":10.73,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "sun":{
                       "sunset":703824633,
                       "astronomicalDusk":703830363,
                       "solarMidnight":703757266,
                       "sunrise":703776360,
                       "astronomicalDawn":703770664,
                       "nauticalDawn":703772739,
                       "civilDawn":703774707,
                       "nauticalDusk":703828271,
                       "solarNoon":703800480,
                       "civilDusk":703826287
                    },
                    "wholeDaySnowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "symbolName":"sun.max",
                    "precipitationChance":0,
                    "precipitation":"none",
                    "uvIndex":{
                       "value":7,
                       "category":"high"
                    },
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703753200,
                    "highTemperature":{
                       "value":21.420000000000002,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "wind":{
                       "speed":{
                          "value":8.8699999999999992,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"westSouthwest",
                       "direction":{
                          "value":255,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    },
                    "moon":{
                       "phase":"waxingCrescent",
                       "moonrise":703779347,
                       "moonset":703832238
                    },
                    "overnightForecast":{
                       "humidity":0.80000000000000004,
                       "condition":"mostlyCloudy",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":204,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.68000000000000005,
                       "windSpeed":{
                          "value":6.1200000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    },
                    "daytimeForecast":{
                       "humidity":0.56999999999999995,
                       "condition":"partlyCloudy",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":262,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.41999999999999998,
                       "windSpeed":{
                          "value":8.0899999999999999,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    },
                    "restOfDayForecast":{
                       "humidity":0.60999999999999999,
                       "condition":"partlyCloudy",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":255,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.55000000000000004,
                       "windSpeed":{
                          "value":8.8699999999999992,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    }
                 },
                 {
                    "rainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "condition":"partlyCloudy",
                    "humidity":0,
                    "wholeDayRainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "lowTemperature":{
                       "value":11.08,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "sun":{
                       "sunset":703911088,
                       "astronomicalDusk":703916840,
                       "solarMidnight":703843654,
                       "sunrise":703862681,
                       "astronomicalDawn":703856965,
                       "nauticalDawn":703859049,
                       "civilDawn":703861025,
                       "nauticalDusk":703914737,
                       "solarNoon":703886868,
                       "civilDusk":703912747
                    },
                    "wholeDaySnowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "symbolName":"cloud.sun",
                    "precipitationChance":0,
                    "precipitation":"none",
                    "uvIndex":{
                       "value":8,
                       "category":"veryHigh"
                    },
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703839600,
                    "highTemperature":{
                       "value":19.969999999999999,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "wind":{
                       "speed":{
                          "value":9.5700000000000003,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"southwest",
                       "direction":{
                          "value":236,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    },
                    "moon":{
                       "phase":"waxingCrescent",
                       "moonrise":703867822,
                       "moonset":703922664
                    },
                    "overnightForecast":{
                       "humidity":0.80000000000000004,
                       "condition":"partlyCloudy",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":216,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.42999999999999999,
                       "windSpeed":{
                          "value":9.5500000000000007,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    },
                    "daytimeForecast":{
                       "humidity":0.66000000000000003,
                       "condition":"mostlyClear",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":236,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.32000000000000001,
                       "windSpeed":{
                          "value":9.5700000000000003,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    }
                 },
                 {
                    "rainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "condition":"mostlyClear",
                    "humidity":0,
                    "wholeDayRainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "lowTemperature":{
                       "value":10.93,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "sun":{
                       "sunset":703997543,
                       "astronomicalDusk":704003318,
                       "solarMidnight":703930042,
                       "sunrise":703949002,
                       "astronomicalDawn":703943267,
                       "nauticalDawn":703945359,
                       "civilDawn":703947343,
                       "nauticalDusk":704001204,
                       "solarNoon":703973256,
                       "civilDusk":703999207
                    },
                    "wholeDaySnowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "symbolName":"sun.max",
                    "precipitationChance":0,
                    "precipitation":"none",
                    "uvIndex":{
                       "value":7,
                       "category":"high"
                    },
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703926000,
                    "highTemperature":{
                       "value":19.219999999999999,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "wind":{
                       "speed":{
                          "value":12.800000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"westSouthwest",
                       "direction":{
                          "value":241,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    },
                    "moon":{
                       "phase":"waxingCrescent",
                       "moonrise":703956638
                    },
                    "overnightForecast":{
                       "humidity":0.79000000000000004,
                       "condition":"partlyCloudy",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":236,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.41999999999999998,
                       "windSpeed":{
                          "value":10.029999999999999,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    },
                    "daytimeForecast":{
                       "humidity":0.69999999999999996,
                       "condition":"mostlyClear",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":241,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.26000000000000001,
                       "windSpeed":{
                          "value":12.800000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    }
                 },
                 {
                    "rainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "condition":"mostlyClear",
                    "humidity":0,
                    "wholeDayRainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "lowTemperature":{
                       "value":9.75,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "sun":{
                       "sunset":704083999,
                       "astronomicalDusk":704089795,
                       "solarMidnight":704016431,
                       "sunrise":704035325,
                       "astronomicalDawn":704029569,
                       "nauticalDawn":704031670,
                       "civilDawn":704033662,
                       "nauticalDusk":704087670,
                       "solarNoon":704059645,
                       "civilDusk":704085667
                    },
                    "wholeDaySnowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "symbolName":"sun.max",
                    "precipitationChance":0,
                    "precipitation":"none",
                    "uvIndex":{
                       "value":8,
                       "category":"veryHigh"
                    },
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":704012400,
                    "highTemperature":{
                       "value":17.510000000000002,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "wind":{
                       "speed":{
                          "value":11.789999999999999,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"southwest",
                       "direction":{
                          "value":234,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    },
                    "moon":{
                       "phase":"waxingCrescent",
                       "moonrise":704045836,
                       "moonset":704012837
                    },
                    "overnightForecast":{
                       "humidity":0.81000000000000005,
                       "condition":"mostlyClear",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":177,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.20000000000000001,
                       "windSpeed":{
                          "value":7.6500000000000004,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    },
                    "daytimeForecast":{
                       "humidity":0.63,
                       "condition":"mostlyClear",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":234,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.17999999999999999,
                       "windSpeed":{
                          "value":11.789999999999999,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    }
                 },
                 {
                    "rainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "condition":"clear",
                    "humidity":0,
                    "wholeDayRainfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "lowTemperature":{
                       "value":9.6500000000000004,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "sun":{
                       "sunset":704170454,
                       "astronomicalDusk":704176273,
                       "solarMidnight":704102821,
                       "sunrise":704121648,
                       "astronomicalDawn":704115871,
                       "nauticalDawn":704117982,
                       "civilDawn":704119982,
                       "nauticalDusk":704174137,
                       "solarNoon":704146035,
                       "civilDusk":704172128
                    },
                    "wholeDaySnowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "symbolName":"sun.max",
                    "precipitationChance":0,
                    "precipitation":"none",
                    "uvIndex":{
                       "value":8,
                       "category":"veryHigh"
                    },
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":704098800,
                    "highTemperature":{
                       "value":20.710000000000001,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "wind":{
                       "speed":{
                          "value":8.6199999999999992,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"westSouthwest",
                       "direction":{
                          "value":250,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    },
                    "moon":{
                       "phase":"waxingCrescent",
                       "moonrise":704135403,
                       "moonset":704102618
                    },
                    "overnightForecast":{
                       "humidity":0.80000000000000004,
                       "condition":"clear",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":191,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0,
                       "windSpeed":{
                          "value":5,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    },
                    "daytimeForecast":{
                       "humidity":0.60999999999999999,
                       "condition":"clear",
                       "snowfallAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "windDirection":{
                          "value":250,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       },
                       "cloudCover":0.12,
                       "windSpeed":{
                          "value":8.6199999999999992,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "precipitationChance":0,
                       "precipitationAmount":{
                          "value":0,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.001
                             },
                             "symbol":"mm"
                          }
                       },
                       "precipitation":"none"
                    }
                 }
              ]
           },
           "hourlyForecast":{
              "metadata":{
                 "attribution":{
                    "combinedMarkDarkURL":"https://weather-data.apple.com/assets/branding/combined-mark-dark.png",
                    "name":"Apple Weather",
                    "combinedMarkLightURL":"https://weather-data.apple.com/assets/branding/combined-mark-light.png",
                    "logoURL":"https://weather-data.apple.com/assets/branding/combined-mark-dark.png",
                    "squareMarkURL":"https://weather-data.apple.com/assets/branding/square-mark.png",
                    "legalPageURL":"https://weather-data.apple.com/legal-attribution.html",
                    "sourceURL":"https://weather-data.apple.com/legal-attribution.html",
                    "serviceName":"Apple Weather"
                 },
                 "expirationDate":703799124,
                 "latitude":37.831000000000003,
                 "longitude":-122.286,
                 "date":703795524
              },
              "forecast":[
                 {
                    "temperature":{
                       "value":13.35,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "condition":"clear",
                    "humidity":0.64000000000000001,
                    "isDaylight":false,
                    "cloudCover":0.01,
                    "symbolName":"moon.stars",
                    "precipitationChance":0,
                    "dewPoint":{
                       "value":6.7199999999999998,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "precipitation":"none",
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703749600,
                    "precipitationAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "pressureTrend":"rising",
                    "uvIndex":{
                       "value":0,
                       "category":"low"
                    },
                    "apparentTemperature":{
                       "value":12.57,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "pressure":{
                       "value":1026.6900000000001,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":100
                          },
                          "symbol":"mbar"
                       }
                    },
                    "visibility":{
                       "value":28520.700000000001,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":1
                          },
                          "symbol":"m"
                       }
                    },
                    "wind":{
                       "gust":{
                          "value":5.1500000000000004,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "speed":{
                          "value":2.7400000000000002,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"north",
                       "direction":{
                          "value":356,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    }
                 },
                 {
                    "temperature":{
                       "value":13.02,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "condition":"mostlyClear",
                    "humidity":0.65000000000000002,
                    "isDaylight":false,
                    "cloudCover":0.14000000000000001,
                    "symbolName":"moon.stars",
                    "precipitationChance":0,
                    "dewPoint":{
                       "value":6.6399999999999997,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "precipitation":"none",
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703753200,
                    "precipitationAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "pressureTrend":"steady",
                    "uvIndex":{
                       "value":0,
                       "category":"low"
                    },
                    "apparentTemperature":{
                       "value":12.24,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "pressure":{
                       "value":1026.45,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":100
                          },
                          "symbol":"mbar"
                       }
                    },
                    "visibility":{
                       "value":28292.700000000001,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":1
                          },
                          "symbol":"m"
                       }
                    },
                    "wind":{
                       "gust":{
                          "value":5.1500000000000004,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "speed":{
                          "value":2.3799999999999999,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"north",
                       "direction":{
                          "value":9,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    }
                 },
                 {
                    "temperature":{
                       "value":12.68,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "condition":"clear",
                    "humidity":0.65000000000000002,
                    "isDaylight":false,
                    "cloudCover":0.089999999999999997,
                    "symbolName":"moon.stars",
                    "precipitationChance":0,
                    "dewPoint":{
                       "value":6.3499999999999996,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "precipitation":"none",
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703756800,
                    "precipitationAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "pressureTrend":"steady",
                    "uvIndex":{
                       "value":0,
                       "category":"low"
                    },
                    "apparentTemperature":{
                       "value":11.890000000000001,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "pressure":{
                       "value":1026.3399999999999,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":100
                          },
                          "symbol":"mbar"
                       }
                    },
                    "visibility":{
                       "value":28261.130000000001,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":1
                          },
                          "symbol":"m"
                       }
                    },
                    "wind":{
                       "gust":{
                          "value":4.5199999999999996,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "speed":{
                          "value":1.5800000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"southSoutheast",
                       "direction":{
                          "value":150,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    }
                 },
                 {
                    "temperature":{
                       "value":11.93,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "condition":"clear",
                    "humidity":0.68000000000000005,
                    "isDaylight":false,
                    "cloudCover":0.029999999999999999,
                    "symbolName":"moon.stars",
                    "precipitationChance":0,
                    "dewPoint":{
                       "value":6.1500000000000004,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "precipitation":"none",
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703760400,
                    "precipitationAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "pressureTrend":"steady",
                    "uvIndex":{
                       "value":0,
                       "category":"low"
                    },
                    "apparentTemperature":{
                       "value":11.140000000000001,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "pressure":{
                       "value":1026.1099999999999,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":100
                          },
                          "symbol":"mbar"
                       }
                    },
                    "visibility":{
                       "value":25335.48,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":1
                          },
                          "symbol":"m"
                       }
                    },
                    "wind":{
                       "gust":{
                          "value":5.0800000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "speed":{
                          "value":3.4100000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"southSoutheast",
                       "direction":{
                          "value":150,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    }
                 },
                 {
                    "temperature":{
                       "value":11.59,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "condition":"mostlyClear",
                    "humidity":0.69999999999999996,
                    "isDaylight":false,
                    "cloudCover":0.16,
                    "symbolName":"moon.stars",
                    "precipitationChance":0,
                    "dewPoint":{
                       "value":6.2599999999999998,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "precipitation":"none",
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703764000,
                    "precipitationAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "pressureTrend":"steady",
                    "uvIndex":{
                       "value":0,
                       "category":"low"
                    },
                    "apparentTemperature":{
                       "value":10.82,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "pressure":{
                       "value":1025.8599999999999,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":100
                          },
                          "symbol":"mbar"
                       }
                    },
                    "visibility":{
                       "value":23898.259999999998,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":1
                          },
                          "symbol":"m"
                       }
                    },
                    "wind":{
                       "gust":{
                          "value":4.6200000000000001,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "speed":{
                          "value":2.4700000000000002,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"southSoutheast",
                       "direction":{
                          "value":152,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    }
                 },
                 {
                    "temperature":{
                       "value":11.25,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "condition":"mostlyClear",
                    "humidity":0.69999999999999996,
                    "isDaylight":false,
                    "cloudCover":0.20999999999999999,
                    "symbolName":"moon.stars",
                    "precipitationChance":0,
                    "dewPoint":{
                       "value":6.0099999999999998,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "precipitation":"none",
                    "snowfallAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "date":703767600,
                    "precipitationAmount":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":0.001
                          },
                          "symbol":"mm"
                       }
                    },
                    "pressureTrend":"steady",
                    "uvIndex":{
                       "value":0,
                       "category":"low"
                    },
                    "apparentTemperature":{
                       "value":10.470000000000001,
                       "unit":{
                          "converter":{
                             "constant":273.14999999999998,
                             "coefficient":1
                          },
                          "symbol":"°C"
                       }
                    },
                    "pressure":{
                       "value":1025.77,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":100
                          },
                          "symbol":"mbar"
                       }
                    },
                    "visibility":{
                       "value":25060.880000000001,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":1
                          },
                          "symbol":"m"
                       }
                    },
                    "wind":{
                       "gust":{
                          "value":4.0999999999999996,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "speed":{
                          "value":1.8999999999999999,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":0.27777800000000002
                             },
                             "symbol":"km/h"
                          }
                       },
                       "compassDirection":"northNortheast",
                       "direction":{
                          "value":25,
                          "unit":{
                             "converter":{
                                "constant":0,
                                "coefficient":1
                             },
                             "symbol":"°"
                          }
                       }
                    }
                 }
              ]
           },
           "appLocationConfig":{
              "expireTime":703797324.72336197,
              "reportAnIssue":{
                 "position":"beforeFooter",
                 "minDaysSinceInteraction":0
              }
           },
           "minuteForecast":{
              "metadata":{
                 "attribution":{
                    "combinedMarkDarkURL":"https://weather-data.apple.com/assets/branding/combined-mark-dark.png",
                    "name":"Apple Weather",
                    "combinedMarkLightURL":"https://weather-data.apple.com/assets/branding/combined-mark-light.png",
                    "logoURL":"https://weather-data.apple.com/assets/branding/combined-mark-dark.png",
                    "squareMarkURL":"https://weather-data.apple.com/assets/branding/square-mark.png",
                    "legalPageURL":"https://weather-data.apple.com/legal-attribution.html",
                    "sourceURL":"https://weather-data.apple.com/legal-attribution.html",
                    "serviceName":"Apple Weather"
                 },
                 "expirationDate":703802724,
                 "latitude":37.831000000000003,
                 "longitude":-122.286,
                 "date":703795524
              },
              "forecast":[
                 {
                    "precipitationIntensity":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":2.7776999999999998e-07
                          },
                          "symbol":"mm/h"
                       }
                    },
                    "precipitationChance":0,
                    "apparentPrecipitationIntensity":{
                       "value":0,
                       "category":"light"
                    },
                    "precipitation":"none",
                    "date":703795500
                 },
                 {
                    "precipitationIntensity":{
                       "value":0,
                       "unit":{
                          "converter":{
                             "constant":0,
                             "coefficient":2.7776999999999998e-07
                          },
                          "symbol":"mm/h"
                       }
                    },
                    "precipitationChance":0,
                    "apparentPrecipitationIntensity":{
                       "value":0,
                       "category":"light"
                    },
                    "precipitation":"none",
                    "date":703795560
                 }
              ],
              "minuteSummary":"",
              "minuteConditions":[
                 
              ],
              "minuteSummaries":[
                 {
                    "apparentPrecipitationIntensity":{
                       "value":0,
                       "category":"light"
                    },
                    "precipitationKind":"none",
                    "precipitationChance":0,
                    "precipitation":"none",
                    "date":703795500
                 }
              ]
           },
           "weatherAlerts":[
              
           ]
        }
  """
		return string
	}
}
